### ISSUE TITLE
No files in repository.

### ISSUE THREAD

**Issue by burque505** [iamshaunjp/JavaScript-DOM-Tutorial#5]
No files usable "as-is in" repository.
I was expecting this:
![shaun1](https://user-images.githubusercontent.com/46876254/70749548-cec20180-1ce9-11ea-900f-2c67245fdc97.PNG)
but found this:
![shaun2](https://user-images.githubusercontent.com/46876254/70749729-2ceee480-1cea-11ea-9cf0-2a72aef06e72.PNG)
Thanks.

**Comment by cpalmer-atx** [comment]
@burque505 You're looking at the master branch.  There's a different branch for each tutorial in his series.  If you look at the screenshots you posted, you'll notice that the 'expected' screenshot says lesson-1 in the Branch pull down.

**Comment by burque505** [comment]
@cpalmer-atx, thanks for clearing that up!
